// <auto-generated />
using GECORO.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GECORO.Persistence.Migrations
{
    [DbContext(typeof(GecoroContext))]
    partial class GecoroContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.9");

            modelBuilder.Entity("GECORO.Domain.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CPF")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("GECORO.Domain.Contrato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NuContrato")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SaldoDevedor")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Contratos");
                });

            modelBuilder.Entity("GECORO.Domain.Parcela", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ContratoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NuParcela")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StParcela")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Valor")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContratoId");

                    b.ToTable("Parcelas");
                });

            modelBuilder.Entity("GECORO.Domain.RegraContrato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ParcelasPagas")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SaldoDevedor")
                        .HasColumnType("TEXT");

                    b.Property<int>("VendedorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("VendedorId")
                        .IsUnique();

                    b.ToTable("RegraContrato");
                });

            modelBuilder.Entity("GECORO.Domain.Vendedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codigo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Vendedores");
                });

            modelBuilder.Entity("GECORO.Domain.VendedorCliente", b =>
                {
                    b.Property<int>("VendedorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.HasKey("VendedorId", "ClienteId");

                    b.HasIndex("ClienteId");

                    b.ToTable("VendedoresClientes");
                });

            modelBuilder.Entity("GECORO.Domain.Contrato", b =>
                {
                    b.HasOne("GECORO.Domain.Cliente", "Cliente")
                        .WithMany("Contratos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("GECORO.Domain.Parcela", b =>
                {
                    b.HasOne("GECORO.Domain.Contrato", null)
                        .WithMany("Parcelas")
                        .HasForeignKey("ContratoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GECORO.Domain.RegraContrato", b =>
                {
                    b.HasOne("GECORO.Domain.Vendedor", "Vendedor")
                        .WithOne("RegraContrato")
                        .HasForeignKey("GECORO.Domain.RegraContrato", "VendedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vendedor");
                });

            modelBuilder.Entity("GECORO.Domain.VendedorCliente", b =>
                {
                    b.HasOne("GECORO.Domain.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GECORO.Domain.Vendedor", "Vendedor")
                        .WithMany("VendedoresClientes")
                        .HasForeignKey("VendedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Vendedor");
                });

            modelBuilder.Entity("GECORO.Domain.Cliente", b =>
                {
                    b.Navigation("Contratos");
                });

            modelBuilder.Entity("GECORO.Domain.Contrato", b =>
                {
                    b.Navigation("Parcelas");
                });

            modelBuilder.Entity("GECORO.Domain.Vendedor", b =>
                {
                    b.Navigation("RegraContrato");

                    b.Navigation("VendedoresClientes");
                });
#pragma warning restore 612, 618
        }
    }
}
